// src/main/java/com/products/audit/domain/AuditAction.java
package com.products.audit.domain;

public enum AuditAction {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  PRODUCT_CREATE, PRODUCT_UPDATE, PRODUCT_DELETE, PRODUCT_READ, PRODUCT_LIST,
  CLIENT_CREATE, CLIENT_UPDATE, CLIENT_DELETE, CLIENT_READ, CLIENT_LIST,
  ORDER_CREATE, ORDER_APPROVE, ORDER_READ, ORDER_LIST,
  USER_CREATE, USER_UPDATE, USER_DELETE, USER_UNLOCK, USER_RESET_PASSWORD,
  GENERIC
}

